spring.application.name=Ci-Cd_fundamentals

# Console log pattern
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} %-5level [%logger{36}] - %msg%n

# Write logs to file
logging.file.name=logs/app.log
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} %-5level [%logger{36}] - %msg%n

# Keep 30 days of log files, max 10MB each
logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.max-history=30
