package Ci_Cd_fundamentals.Ci_Cd_fundamentals;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RestController;

@RestController
public class HelloController {

    private static final Logger log = LoggerFactory.getLogger(HelloController.class);

    @GetMapping("/")
    public String home() {
        log.info("Request received: GET /");
        return "Welcome to my CI/CD Pipeline Project!";
    }

    @GetMapping("/health")
    public String health() {
        log.info("Request received: GET /health");
        return "OK";
    }

    @GetMapping("/error-test")
    public ResponseEntity<String> errorTest() {
        log.info("Request received: GET /error-test");
        log.error("ERROR TEST: Deliberate application error generated by /error-test");
        return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR).body("Test error generated");
    }
}
